version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aakefi/foyer-app:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/foyer?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8086:8086"   # Spring Boot app
      - "9404:9404"   # Prometheus metrics (if used)
    # depends_on is for service startup order within this compose file.
    # Since mysql, nexus, and sonarqube are running externally, 
    # we rely on their external availability.
    # The names 'mysql', 'nexus', 'sonarqube' should resolve via Docker's internal DNS
    # if they are on the same network as this 'app' service.
    networks:
      - backend
      - monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/Foyer/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend:
    external: true
  monitoring:
    external: true
