version: '3.8'

services:
  # Spring Boot App (Updated for Java 17)
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: aakefi/foyer-app:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/foyer?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8086:8086"  # Matches your application.properties
      - "9404:9404"   # Prometheus metrics
    networks:
      - backend
      - monitoring
    depends_on:
      mysql:
        condition: service_healthy
      nexus:
      sonarqube:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/Foyer/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MySQL Database (Replaced PostgreSQL)
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: foyer
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # CI/CD Services
  jenkins:
    image: jenkins/jenkins:lts
    user: root  # Temporary for Docker access
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "49000:8080"
      - "50000:50000"
    networks:
      - backend
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    hostname: sonarqube
    ports:
      - "9000:9000"
    networks:
      - backend
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - backend

  # Monitoring Stack
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  jenkins_data:
  nexus_data:
  mysql_data:
  grafana_data:
  sonarqube_data:
  sonarqube_extensions:
networks:
  backend:
    driver: bridge
  monitoring:
    driver: bridge
