global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'foyer-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['foyer-app:8080']
    scrape_interval: 30s

  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8080']
    metrics_path: '/prometheus'

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
