global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-app-actuator'
    metrics_path: '/Foyer/actuator/prometheus'
    static_configs:
      - targets: ['foyer-app:8086']
    scrape_interval: 5s

  - job_name: 'spring-app-otel'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['foyer-app:9464']
    scrape_interval: 5s

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
